package com.simonecavazzoni.algraph.controller;

import javafx.scene.input.KeyEvent;
import javafx.scene.layout.Pane;

public abstract class Controller {

    /**
     * Set of callbacks for controller events
     */
    public interface EventListener {
        /**
         * Callback called when a key is pressed
         * @param event Event generated by keypress
         */
        void onKeyPressed(KeyEvent event);
    }

    /**
     * Controller root view
     */
    protected Pane root;

    public final Pane get() {
        return this.root;
    }

    protected void setRoot(Pane root) {
        this.root = root;
        this.root.getStyleClass().add("controllerRoot");
    }
}
