package com.simonecavazzoni.algraph.controller;

import javafx.scene.input.KeyEvent;
import javafx.scene.layout.Pane;

/**
 * Super class for program controllers.
 */
public abstract class Controller {

    /**
     * Set of callbacks for controller events
     */
    public interface EventListener {
        /**
         * Callback called when a key is pressed
         * @param event Event generated by keypress
         */
        void onKeyPressed(KeyEvent event);
    }

    /**
     * Controller root view
     */
    protected Pane root;

    /**
     * Returns controller root view.
     * @return Controller root pane
     */
    public final Pane get() {
        return this.root;
    }

    /**
     * Sets a new pane as root and adds css to it.
     * @param root Pane to set as root
     */
    protected void setRoot(Pane root) {
        this.root = root;
        this.root.getStyleClass().add("controllerRoot");
    }
}
